jdbc:
  driverClassname: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/springboor_test
  username: root
  password: root
spring:
  profiles:
    active: abc
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_test
    username: root
    password: root
server:
  port: 80
mybatis:
  #  实体类别名包路径
  type-aliases-package: com.itheima.pojo
  #映射文件路径
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl